load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "Vengai-test",
    srcs = [
        "main.cpp",
    ],
    # linkopts = [
    #     "-lsfml-graphics",
    #     "-lsfml-window",
    #     "-lsfml-system",
    # ],
    deps = [
        "//src:Vengai",
    ]
)
