load("@rules_cc//cc:defs.bzl", "cc_library")



cc_library(
    name = "Vengai",
    srcs = [
        "Vengai.hpp",
    ],
    visibility = ["//visibility:public"],
    # linkopts = [
    #     "-lsfml-graphics",
    #     "-lsfml-window",
    #     "-lsfml-system",
    # ],
)
